from __future__ import annotations

from .models import AutomationDocument, DetailItem


def render_markdown(documents: list[AutomationDocument]) -> str:
    lines = [
        "<!-- Generated by automation-docs. Do not edit manually; rerun the exporter. -->",
        "",
        "This file is a deterministic extraction from Salesforce XML metadata. It is intended as the raw documentation layer for later AI analysis into business-facing automation documentation.",
        "",
        "## Summary",
        "",
        f"- Automations documented: {len(documents)}",
        "",
    ]

    for document in documents:
        lines.extend(_render_document(document))

    return "\n".join(lines).rstrip() + "\n"


def _render_document(document: AutomationDocument) -> list[str]:
    lines = [
        f"# {_escape_heading(document.title)}",
        "",
        "## Automation identity",
        "",
    ]
    lines.extend(_key_values(document.identity))
    lines.extend(
        _section(
            "Entry Criteria",
            (
                ("XML Criteria", _detail_items(document.entry_criteria)),
            ),
        )
    )
    lines.extend(
        _section(
            "Automation Logic",
            (
                ("Elements", _detail_items(document.automation_logic)),
                ("Scheduled and Wait Paths", _detail_items(document.scheduled_paths)),
                ("Connector Graph", _bullets(document.connectors or ("No connector graph entries found.",))),
            ),
        )
    )
    lines.extend(
        _section(
            "Data and Side Effects",
            (
                ("Data Changes", _detail_items(document.data_changes)),
                ("Side Effects", _detail_items(document.side_effects)),
                ("Resources", _detail_items(document.resources)),
                ("Dependencies", _bullets(document.dependencies)),
            ),
        )
    )
    lines.extend(
        _section(
            "Operational Trust",
            (
                ("Error Handling and Observability", _detail_items(document.error_handling)),
                ("Testing and Validation", _bullets(document.testing_notes)),
                ("Change Notes", _bullets(document.change_notes)),
            ),
        )
    )
    lines.extend(
        _section(
            "XML Extraction Detail",
            (
                ("Raw Element Inventory", _detail_items(document.raw_inventory)),
            ),
        )
    )
    return lines


def _section(title: str, subsections: tuple[tuple[str, list[str]], ...]) -> list[str]:
    lines = ["", f"## {title}", ""]
    for subtitle, content in subsections:
        lines.extend([f"### {subtitle}", ""])
        lines.extend(content or ["- Not found in XML."])
        lines.append("")
    return lines


def _key_values(items: tuple[tuple[str, str], ...]) -> list[str]:
    return [f"- **{key}:** {value}" for key, value in items]


def _bullets(items: tuple[str, ...]) -> list[str]:
    return [f"- {item}" for item in items]


def _detail_items(items: tuple[DetailItem, ...]) -> list[str]:
    lines: list[str] = []
    for item in items:
        lines.append(f"- **{item.name}**")
        for detail in item.details:
            lines.append(f"  - {detail}")
    return lines


def _escape_heading(value: str) -> str:
    return value.replace("\n", " ").strip()
